categories = {   'Auto': ['Gas', 'Other_Auto'],
    'Baby': ['Diapers', 'Formula', 'Other_Baby', 'Toys'],
    'Bank_Internal_Processing': ['Internal_Codes'],
    'Business_Services': ['IT_Services', 'Consulting'],
    'Clothes': ['Clothes_Clothes', 'Shoes', 'Jewelry', 'Bags_Accessories'],
    'Credit_Card_Loan_Payments': [   'Credit_Card_Payment',
                                     'Auto_Loan_Payment',
                                     'BNPL',
                                     'Installment_Loan',
                                     'Zelle_P2P_Received',
                                     'Deposit',
                                     'Interest_Income'],
    'Debt_Collection': ['Collections_Agencies'],
    'Digital_Payments': ['UPI'],
    'Education': ['Educational_Services'],
    'Electronics': ['Electronics_misc', 'Accessories', 'Computer', 'TV', 'Tablet_Watch'],
    'Entertainment': ['Arts_Crafts', 'Games', 'Guns', 'DateNights', 'E_Other'],
    'Fees_Interest': ['Bank_Fees', 'Interest_Charged_Purchases'],
    'Food': ['Dining_Restaurants', 'Food_Delivery', 'Fast_Food', 'Groceries'],
    'Government_Services': ['Fees_and_Charges'],
    'Home': [   'Rent',
                'Decor',
                'Furniture_Appliances',
                'Home_Essentials',
                'Hygiene',
                'Kitchen',
                'Security',
                'Tools',
                'Yard_Garden'],
    'Income_Credits': ['Payroll_Income'],
    'Investments_Crypto': ['Brokerage_Investments', 'Crypto_Exchange', 'Dividends'],
    'Kids': ['K_Toys'],
    'Legal_Government': ['Court_Ticket_Payments', 'Tax_Payments_Refunds'],
    'Locker_Services': ['Locker_Charges'],
    'Medical': ['Health_Wellness', 'Vision_Dental'],
    'P2P_Digital_Wallets': ['Paytm', 'Razorpay'],
    'Person_To_Person': ['Individual_Transfers'],
    'Personal_Care': ['Hair', 'Beauty', 'Vitamins_Supplements', 'Makeup_Nails', 'PC_Other'],
    'Pets': ['Pet_Food', 'Pet_Grooming', 'Pet_Med', 'Pet_Other', 'Pet_Toys'],
    'Refunds': ['Purchase_Refund'],
    'Retirement_Savings': ['Pension_Provident_Fund'],
    'Shopping': ['General_Merchandise', 'POS_Purchases'],
    'Subscriptions_Memberships': ['Sub_Other'],
    'Transfers_Internal_Movement': [   'Bank_Transfer_To_Checking',
                                       'Bank_Transfer_From_Checking',
                                       'Bank_Transfer_From_Savings',
                                       'Overdraft_Protection',
                                       'Keep_the_Change_Transfer',
                                       'External_Transfer',
                                       'ATM_Transaction'],
    'Travel': ['Activities', 'Ride_Sharing', 'Flights', 'Hotels', 'Car_Rental', 'Travel_Services'],
    'Unclassified_Miscellaneous': ['Other_Services', 'Unknown'],
    'Utilities_Recurring_Bills': ['Electric', 'Insurance', 'Phone_Internet', 'Cable_TV']}
