categories = {
    'Auto': ['Gas', 'Auto_Maintenance', 'Other_Auto', 'Maintenance'],
    'Baby': ['Baby_Clothes', 'Diapers', 'Formula', 'Other_Baby', 'Toys'],
    'Bank_Internal_Processing': ['Internal_Codes'],
    'Business_Services': ['IT_Services', 'Consulting'],
    'Clothes': ['Bags_Accessories', 'Clothes_Clothes', 'Jewelry', 'Shoes'],
    'Credit_Card_Loan_Payments': ['Auto_Loan_Payment', 'BNPL', 'Credit_Card_Payment', 'Deposit', 'Installment_Loan', 'Interest_Income', 'Zelle_P2P_Received'],
    'Debt_Collection': ['Collections_Agencies'],
    'Digital_Payments': ['QR_Code', 'UPI'],
    'Education': ['Educational_Services'],
    'Electronics': ['Accessories', 'Computer', 'Electronics_misc', 'TV', 'Tablet_Watch'],
    'Entertainment': ['Arts_Crafts', 'Books', 'DateNights', 'E_Other', 'Entertainment_Sports_Outdoors', 'Games', 'Guns', 'Movies_TV', 'Sports_Outdoors'],
    'Fees_Interest': ['Bank_Fees', 'Interest_Charged_Cash_Advance', 'Interest_Charged_Purchases'],
    'Food': ['Dining_Restaurants', 'Fast_Food', 'Food_Delivery', 'Groceries'],
    'Government_Services': ['Fees_and_Charges'],
    'Home': ['Decor', 'Furniture_Appliances', 'Home_Essentials', 'Home_Gym', 'Home_Maintenance', 'Hygiene', 'Kitchen', 'Rent', 'Security', 'Tools', 'Yard_Garden', 'Maintenance'],
    'Income_Credits': ['Cashback_Statement_Credits', 'Deposit', 'Interest_Income', 'Payroll_Income', 'Zelle_P2P_Received'],
    'Investments_Crypto': ['Brokerage_Investments', 'Crypto_Exchange', 'Dividends'],
    'Kids': ['K_Toys'],
    'Legal_Government': ['Court_Ticket_Payments', 'Tax_Payments_Refunds'],
    'Locker_Services': ['Locker_Charges'],
    'Medical': ['Health_Wellness', 'Vision_Dental'],
    'Mobile_Payments': ['Mobile_Payments'],
    'P2P_Digital_Wallets': ['Cash_App', 'Paytm', 'Razorpay', 'Venmo', 'Zelle'],
    'Person_To_Person': ['Individual_Transfers'],
    'Personal_Care': ['Beauty', 'Hair', 'Makeup_Nails', 'Massage', 'PC_Other', 'Personal_Care_Sports_Outdoors', 'Vitamins_Supplements'],
    'Pets': ['Pet_Food', 'Pet_Grooming', 'Pet_Med', 'Pet_Other', 'Pet_Toys'],
    'Refunds': ['Purchase_Refund'],
    'Retirement_Savings': ['Pension_Provident_Fund'],
    'Shopping': ['Clothes', 'General_Merchandise', 'POS_Purchases'],
    'Subscriptions_Memberships': ['Entertainment', 'Gym', 'Sub_Other', 'Subscriptions_Memberships_Gym'],
    'Transfers_Internal_Movement': ['ATM_Transaction', 'Bank_Transfer_From_Checking', 'Bank_Transfer_From_Savings', 'Bank_Transfer_To_Checking', 'Bank_Transfer_To_Savings', 'External_Transfer', 'Keep_the_Change_Transfer', 'Overdraft_Protection'],
    'Travel': ['Activities', 'Car_Rental', 'Flights', 'Hotels', 'Rail', 'Ride_Sharing', 'Travel_Services'],
    'Unclassified_Miscellaneous': ['Other_Services', 'Unknown'],
    'Utilities_Recurring_Bills': ['Cable_TV', 'Electric', 'Insurance', 'Phone_Internet']
}
